sudo: false  
language: go  
git:  
    depth: 1  
install: go get -v github.com/gohugoio/hugo  
script:  
    ‐ hugo  
deploy:  
    provider: pages  
    skip_cleanup: true  
    github_token: $GITHUB_TOKEN  
    on:  
        branch: master  
    local_dir: public  
    repo: meroco/meroco.github.io  
    fqdn: mint.moe  
    target_branch: master  
    email: meroco.xu@gmail.com  
    name: meroco 
