baseurl = "https://mint.moe/"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "Ornithopter"
theme = "dream"

# copyright = ""

googleAnalytics = "UA-82270338-1"

disqusShortname = "misuzu"

enableRobotsTXT = true

hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  # background = "black"
  backgroundImage = "/bg.jpg"
  linkColor = "babyblue"

  author = "MEROCO"
  description = "摄影/绘画"
  avatar = "https://i.loli.net/2020/02/19/KA8s59VWo1ZyRkP.png"
  motto = "See you, space cowboy..."
  categoriesLimitInHeader = 5

  rss = true

  # utterancesRepo = ""
  
  email = "meroco.xu@gmail.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # github = ""
  weibo = "meroco"
  qq = "6533419"

  siteStartYear = 2016

  favicon = "https://i.loli.net/2020/02/20/Sqf9cNiLoZ3z781.png"
  
  highlightjs = true
    # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
    highlightjsTheme = "gruvbox-light"
    highlightjsThemeDark = "gruvbox-dark"

  # options
  showSummaryCoverInPost = true
  
  # search
  enableSearch = true

  # dark mode
  darkLinkColor = "aqua"
  darkNav = true 
  dark404 = true

